### ISSUE TITLE
Cancel Bills

### ISSUE THREAD

**Issue by whyvrafvr** [trendev/kiam-webapp#7]
# Bill must be cancelled
At the present time, saved Bill can be exported but cannot be cancelled...

**TODO :**
- [x] implement the cancelBill() functions + the corresponding services functions
- [x] block cancelled bill further modifications
- [x] control a cancelled bill cannot be edited/modified anymore (API side)
- [x] update the bill status component with the new status (cancelled)
- [x] update the bills revenue/vat computation skipping cancelled bills
- [x] control on bills component and micro bills compoments
- [x] update webapp & API : cancel bill if not canceled
- [x] clean revenue sum-up
